from fastapi.responses import HTMLResponse


HTML = """
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Metrics Monitoring Prototype</title>
<style>body{font-family:Inter,system-ui,sans-serif;margin:0;background:#f6f8fb;color:#17202a}main{max-width:960px;margin:auto;padding:32px 20px}section{background:white;border:1px solid #d8dee4;border-radius:8px;padding:18px}.row{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}label{display:block;font-weight:650;margin:12px 0 6px}input,select{box-sizing:border-box;width:100%;border:1px solid #b8c2cc;border-radius:6px;padding:10px;font:inherit}button{min-height:38px;padding:0 14px;border-radius:6px;border:1px solid #0369a1;background:#0284c7;color:white;font-weight:650}.actions{display:flex;gap:10px;margin-top:14px;flex-wrap:wrap}.result{background:#f8fafc;border:1px solid #d8dee4;border-radius:6px;padding:12px;margin-top:14px;white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:760px){.row{grid-template-columns:1fr}}</style></head><body><main><h1>Metrics Monitoring</h1><p>Ingest metric points, query time series, create alert rules, and evaluate latest samples.</p><section><div class="row"><div><label>Metric</label><input id="metric" value="cpu"></div><div><label>Value</label><input id="value" type="number" value="91"></div><div><label>Threshold</label><input id="threshold" type="number" value="80"></div><div><label>Direction</label><select id="direction"><option value="above">Above</option><option value="below">Below</option></select></div></div><div class="actions"><button id="ingest">Ingest</button><button id="query">Query</button><button id="alert">Create alert</button><button id="eval">Evaluate</button></div><div id="result" class="result">Results appear here.</div></section></main>
<script>const out=v=>result.textContent=JSON.stringify(v,null,2);async function json(path,opt={}){const r=await fetch(path,{headers:{"content-type":"application/json"},...opt});const b=await r.json();if(!r.ok)throw b;return b}ingest.onclick=async()=>{try{out(await json("/metrics",{method:"POST",body:JSON.stringify({name:metric.value,value:Number(value.value)})}))}catch(e){out(e)}};query.onclick=async()=>{try{out(await json(`/metrics/${encodeURIComponent(metric.value)}`))}catch(e){out(e)}};alert.onclick=async()=>{try{out(await json("/alerts",{method:"POST",body:JSON.stringify({name:"high "+metric.value,metric:metric.value,threshold:Number(threshold.value),direction:direction.value})}))}catch(e){out(e)}};eval.onclick=async()=>{try{out(await json("/alerts/evaluate",{method:"POST"}))}catch(e){out(e)}};</script></body></html>
"""


def ui_response() -> HTMLResponse:
    return HTMLResponse(HTML)
