from fastapi.responses import HTMLResponse


HTML = """
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Payment System Prototype</title>
<style>body{font-family:Inter,system-ui,sans-serif;margin:0;background:#f7f8fb;color:#17202a}main{max-width:960px;margin:auto;padding:32px 20px}section{background:white;border:1px solid #d8dee4;border-radius:8px;padding:18px}.row{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}label{display:block;font-weight:650;margin:12px 0 6px}input{box-sizing:border-box;width:100%;border:1px solid #b8c2cc;border-radius:6px;padding:10px;font:inherit}button{min-height:38px;padding:0 14px;border-radius:6px;border:1px solid #0f766e;background:#0d9488;color:white;font-weight:650}.actions{display:flex;gap:10px;margin-top:14px;flex-wrap:wrap}.result{background:#f8fafc;border:1px solid #d8dee4;border-radius:6px;padding:12px;margin-top:14px;white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:760px){.row{grid-template-columns:1fr}}</style></head><body><main><h1>Payment System</h1><p>Create payment methods, capture idempotent payments, refund, and inspect ledger entries.</p><section><div class="row"><div><label>User</label><input id="user" value="alice"></div><div><label>Merchant</label><input id="merchant" value="store-1"></div><div><label>Amount cents</label><input id="amount" type="number" value="1299"></div><div><label>Idempotency key</label><input id="idem" value="pay-1"></div></div><label>Payment id</label><input id="payment"><div class="actions"><button id="method">Add method</button><button id="pay">Pay</button><button id="refund">Refund</button><button id="ledger">Ledger</button></div><div id="result" class="result">Results appear here.</div></section></main>
<script>const out=v=>result.textContent=JSON.stringify(v,null,2);async function json(path,opt={}){const r=await fetch(path,{headers:{"content-type":"application/json",...(opt.headers||{})},...opt});const b=await r.json();if(!r.ok)throw b;return b}method.onclick=async()=>{try{out(await json("/payment-methods",{method:"POST",body:JSON.stringify({userId:user.value,token:"tok_demo",brand:"visa",last4:"4242"})}))}catch(e){out(e)}};pay.onclick=async()=>{try{const b=await json("/payments",{method:"POST",headers:{"Idempotency-Key":idem.value},body:JSON.stringify({userId:user.value,merchantId:merchant.value,amountCents:Number(amount.value),currency:"USD"})});payment.value=b.paymentId;out(b)}catch(e){out(e)}};refund.onclick=async()=>{try{out(await json(`/payments/${payment.value}/refund`,{method:"POST"}))}catch(e){out(e)}};ledger.onclick=async()=>{try{out(await json(`/payments/${payment.value}/ledger`))}catch(e){out(e)}};</script></body></html>
"""


def ui_response() -> HTMLResponse:
    return HTMLResponse(HTML)
